// frontend/src/components/Navbar.vue
<template>
  <header class="navbar" :class="{ 'navbar--scrolled': isScrolled }">
    <div class="navbar__container container">
      <!-- Logo -->
      <router-link to="/" class="navbar__logo">
        <img src="/images/logo lazis pln.png" alt="Lazis PLN Batam" class="navbar__logo-img" />
      </router-link>

      <!-- Desktop Nav -->
      <nav class="navbar__nav" :class="{ 'navbar__nav--open': menuOpen }">
        <a href="#programs" class="navbar__link" @click="closeMenu">Program Kami</a>
        <a href="#about" class="navbar__link" @click="closeMenu">Tentang Kami</a>
        <a href="#zakat-calculator" class="navbar__link" @click="closeMenu">Hitung Zakat</a>
        <a href="#faq" class="navbar__link" @click="closeMenu">FAQ</a>
        <a href="#" class="navbar__link" @click="closeMenu">Login</a>
        <a href="#zakat-calculator" class="btn btn-gold navbar__cta-mobile" @click="closeMenu">Donasi Sekarang</a>
      </nav>

      <!-- CTA Button -->
      <a href="#zakat-calculator" class="btn btn-gold navbar__cta">
        Donasi Sekarang
      </a>

      <!-- Hamburger -->
      <button class="navbar__hamburger" @click="toggleMenu" :class="{ 'navbar__hamburger--open': menuOpen }" aria-label="Menu">
        <span></span>
        <span></span>
        <span></span>
      </button>
    </div>
  </header>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const isScrolled = ref(false)
const menuOpen = ref(false)

const handleScroll = () => {
  isScrolled.value = window.scrollY > 50
}

const toggleMenu = () => {
  menuOpen.value = !menuOpen.value
  document.body.style.overflow = menuOpen.value ? 'hidden' : ''
}

const closeMenu = () => {
  menuOpen.value = false
  document.body.style.overflow = ''
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<style scoped>
.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  padding: 1rem 0;
  transition: all var(--transition-base);
  background: transparent;
}

.navbar--scrolled {
  background: rgba(10, 46, 60, 0.95);
  backdrop-filter: blur(12px);
  padding: 0.6rem 0;
  box-shadow: 0 2px 20px rgba(0, 0, 0, 0.3);
}

.navbar__container {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.navbar__logo {
  display: flex;
  align-items: center;
  z-index: 1001;
}

.navbar__logo-img {
  height: 40px;
  width: auto;
  padding: 0.35rem 0.6rem;
  background: var(--color-white);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-sm);
}

.navbar__nav {
  display: flex;
  align-items: center;
  gap: 2rem;
}

.navbar__link {
  color: rgba(255, 255, 255, 0.85);
  font-size: var(--text-sm);
  font-weight: 500;
  position: relative;
  padding: 0.25rem 0;
  transition: color var(--transition-fast);
}

.navbar__link::after {
  content: '';
  position: absolute;
  bottom: -2px;
  left: 0;
  width: 0;
  height: 2px;
  background: var(--color-gold);
  transition: width var(--transition-base);
}

.navbar__link:hover {
  color: var(--color-white);
}

.navbar__link:hover::after {
  width: 100%;
}

.navbar__cta {
  padding: 0.6rem 1.5rem;
  font-size: var(--text-sm);
}

.navbar__cta-mobile {
  display: none;
}

/* Hamburger */
.navbar__hamburger {
  display: none;
  flex-direction: column;
  gap: 5px;
  padding: 4px;
  z-index: 1001;
}

.navbar__hamburger span {
  display: block;
  width: 24px;
  height: 2px;
  background: var(--color-white);
  border-radius: 2px;
  transition: all var(--transition-base);
}

.navbar__hamburger--open span:nth-child(1) {
  transform: rotate(45deg) translate(5px, 5px);
}

.navbar__hamburger--open span:nth-child(2) {
  opacity: 0;
}

.navbar__hamburger--open span:nth-child(3) {
  transform: rotate(-45deg) translate(5px, -5px);
}

/* Mobile */
@media (max-width: 900px) {
  .navbar__nav {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    flex-direction: column;
    justify-content: center;
    background: rgba(10, 46, 60, 0.98);
    backdrop-filter: blur(16px);
    gap: 1.5rem;
    transform: translateX(100%);
    transition: transform var(--transition-slow);
  }

  .navbar__nav--open {
    transform: translateX(0);
  }

  .navbar__link {
    font-size: var(--text-lg);
  }

  .navbar__cta {
    display: none;
  }

  .navbar__cta-mobile {
    display: inline-flex;
    margin-top: 1rem;
  }

  .navbar__hamburger {
    display: flex;
  }
}
</style>

// frontend/components/layout/Navbar.jsx
'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Navbar() {
  const [isScrolled, setIsScrolled] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)

  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 50)
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  const closeMenu = () => {
    setMenuOpen(false)
    document.body.style.overflow = ''
  }

  const toggleMenu = () => {
    setMenuOpen((open) => {
      const next = !open
      document.body.style.overflow = next ? 'hidden' : ''
      return next
    })
  }

  return (
    <header
      className={`fixed inset-x-0 top-0 z-[1000] py-4 transition-all duration-300 ${
        isScrolled ? 'bg-navy-dark/95 py-2.5 shadow-[0_2px_20px_rgba(0,0,0,0.3)] backdrop-blur-md' : 'bg-transparent'
      }`}
    >
      <div className="container flex items-center justify-between">
        {/* Logo */}
        <Link href="/" className="z-[1001] flex items-center">
          <img
            src="/images/logo lazis pln.png"
            alt="Lazis PLN Batam"
            className="h-10 w-auto rounded-lg bg-white px-2.5 py-1.5 shadow-sm"
          />
        </Link>

        {/* Desktop Nav */}
        <nav
          className={`flex items-center gap-8 max-[900px]:fixed max-[900px]:inset-0 max-[900px]:flex-col max-[900px]:justify-center max-[900px]:gap-6 max-[900px]:bg-navy-dark/[0.98] max-[900px]:backdrop-blur-lg max-[900px]:transition-transform max-[900px]:duration-400 ${
            menuOpen ? 'max-[900px]:translate-x-0' : 'max-[900px]:translate-x-full'
          }`}
        >
          <a href="#programs" className="navbar-link" onClick={closeMenu}>
            Program Kami
          </a>
          <a href="#" className="navbar-link" onClick={closeMenu}>
            Blog
          </a>
          <a href="#" className="navbar-link" onClick={closeMenu}>
            Tentang Kami
          </a>
          <a href="#" className="navbar-link" onClick={closeMenu}>
            Daftar Program
          </a>
          <a href="#zakat-calculator" className="navbar-link" onClick={closeMenu}>
            Kalkulator Zakat
          </a>
          <a href="#faq" className="navbar-link" onClick={closeMenu}>
            Konsultasi
          </a>
          <div className="hidden items-center gap-5 max-[900px]:mt-4 max-[900px]:flex">
            <a href="#" className="text-sm font-medium text-white/85 hover:text-white" onClick={closeMenu}>
              Login
            </a>
            <a href="#" className="btn btn-gold" onClick={closeMenu}>
              Register
            </a>
          </div>
        </nav>

        {/* Auth (desktop) */}
        <div className="flex items-center gap-5 max-[900px]:hidden">
          <a href="#" className="text-sm font-medium text-white/85 hover:text-white">
            Login
          </a>
          <a href="#" className="btn btn-gold px-6 py-2.5 text-sm">
            Register
          </a>
        </div>

        {/* Hamburger */}
        <button
          onClick={toggleMenu}
          aria-label="Menu"
          className="z-[1001] hidden flex-col gap-[5px] p-1 max-[900px]:flex"
        >
          <span
            className={`block h-0.5 w-6 rounded bg-white transition-transform duration-300 ${
              menuOpen ? 'translate-x-[5px] translate-y-[5px] rotate-45' : ''
            }`}
          />
          <span className={`block h-0.5 w-6 rounded bg-white transition-opacity duration-300 ${menuOpen ? 'opacity-0' : ''}`} />
          <span
            className={`block h-0.5 w-6 rounded bg-white transition-transform duration-300 ${
              menuOpen ? 'translate-x-[5px] -translate-y-[5px] -rotate-45' : ''
            }`}
          />
        </button>
      </div>
    </header>
  )
}
