// frontend/components/sections/HeroSection.jsx
'use client'

import { useEffect, useState } from 'react'

const STATS = [
  { value: 3800000000, prefix: 'Rp ', suffix: ' M', label: 'Dana Terkumpul ZIS', divisor: 1000000 },
  { value: 1240, prefix: '', suffix: '+', label: 'Donatur Aktif' },
  { value: 5600, prefix: '', suffix: '+', label: 'Penerima Manfaat' },
  { value: 100, prefix: '', suffix: '%', label: 'Transparansi Dana' },
]

const FEATURES = [
  {
    title: 'Lembaga Amil Zakat',
    desc: 'Resmi terdaftar dan diakui sebagai lembaga amil zakat yang amanah dan profesional.',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M12 22s-8-4.5-8-11.8A8 8 0 0112 2a8 8 0 018 8.2c0 7.3-8 11.8-8 11.8z" />
        <circle cx="12" cy="10" r="3" />
      </svg>
    ),
  },
  {
    title: 'Donasi Mudah',
    desc: 'Proses donasi yang mudah dan cepat untuk menyalurkan zakat, infaq, dan shadaqah Anda.',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2" />
        <circle cx="9" cy="7" r="4" />
        <path d="M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75" />
      </svg>
    ),
  },
  {
    title: 'Transparan',
    desc: 'Laporan penyaluran dana yang transparan dan dapat diakses oleh seluruh donatur.',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
  },
]

export default function HeroSection() {
  const [displays, setDisplays] = useState(STATS.map(() => '0'))

  useEffect(() => {
    const timer = setTimeout(() => {
      STATS.forEach((stat, index) => {
        let current = 0
        const target = stat.divisor ? stat.value / stat.divisor : stat.value
        const increment = target / 60
        const interval = setInterval(() => {
          current += increment
          if (current >= target) {
            current = target
            clearInterval(interval)
          }
          const text = stat.divisor
            ? `${stat.prefix}${(current / 1000).toFixed(1)}${stat.suffix}`
            : `${stat.prefix}${Math.floor(current).toLocaleString('id-ID')}${stat.suffix}`
          setDisplays((prev) => {
            const next = [...prev]
            next[index] = text
            return next
          })
        }, 16)
      })
    }, 500)
    return () => clearTimeout(timer)
  }, [])

  return (
    <section id="top" className="relative flex min-h-screen items-end overflow-hidden pb-12 max-[600px]:min-h-0 max-[600px]:pb-12">
      {/* Background */}
      <div className="absolute inset-0 z-0">
        <img src="/images/hero-bg.png" alt="Masjid" className="h-full w-full object-cover" />
        <div className="absolute inset-0 bg-gradient-to-br from-[rgba(10,46,60,0.92)] via-[rgba(10,126,126,0.75)] to-[rgba(10,46,60,0.85)]" />
      </div>

      <div className="container relative z-[1] pt-[120px] max-[600px]:pt-[100px]">
        {/* Content */}
        <div className="max-w-[650px] animate-fade-in-up">
          <p className="mb-4 text-xs font-semibold uppercase tracking-[2px] text-gold">
            LAZIS PLN BATAM &mdash; LEMBAGA ZAKAT, INFAQ &amp; SHADAQAH
          </p>
          <h1 className="mb-6 font-heading text-[3rem] font-extrabold leading-[1.15] text-white max-[768px]:text-4xl max-[480px]:text-[1.875rem]">
            Bergabunglah Bersama
            <br />
            kami dalam Misi <span className="italic text-gold">Kebaikan</span>
          </h1>
          <p className="mb-8 max-w-[520px] text-lg leading-[1.7] text-white/80">
            Kami berkomitmen untuk menyalurkan kebaikan bagi yang membutuhkan melalui program-program sosial
            transparan dan terpercaya.
          </p>
          <div className="mb-16 flex flex-wrap gap-4 max-[600px]:flex-col">
            <a href="#zakat-calculator" className="btn btn-gold">
              <svg viewBox="0 0 20 20" fill="currentColor" width="16" height="16">
                <path d="M10 2a8 8 0 100 16 8 8 0 000-16zm1 11H9v-2h2v2zm0-4H9V5h2v4z" />
              </svg>
              Tunaikan Zakat
            </a>
            <a href="#programs" className="btn btn-primary">
              Jelajahi Kami
            </a>
            <a href="#" className="btn btn-outline">
              Infaq / Shodaqoh
            </a>
          </div>
        </div>

        {/* Feature Cards */}
        <div
          className="mb-12 grid animate-fade-in-up grid-cols-3 gap-6 opacity-0 max-[900px]:grid-cols-1"
          style={{ animationDelay: '0.3s' }}
        >
          {FEATURES.map((f) => (
            <div
              key={f.title}
              className="flex gap-4 rounded-xl border border-white/[0.12] bg-white/[0.08] p-6 backdrop-blur-md transition-all hover:-translate-y-1 hover:bg-white/[0.14] hover:shadow-[0_8px_32px_rgba(0,0,0,0.2)]"
            >
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-gold/[0.15] text-gold [&>svg]:h-[22px] [&>svg]:w-[22px]">
                {f.icon}
              </div>
              <div>
                <h4 className="mb-1 text-sm font-bold text-white">{f.title}</h4>
                <p className="text-xs leading-[1.5] text-white/60">{f.desc}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Stats */}
        <div
          className="grid animate-fade-in-up grid-cols-4 gap-6 rounded-2xl border border-white/10 bg-white/[0.06] px-12 py-8 opacity-0 backdrop-blur-md max-[900px]:grid-cols-2 max-[600px]:p-6"
          style={{ animationDelay: '0.6s' }}
        >
          {STATS.map((stat, i) => (
            <div key={stat.label} className="text-center">
              <span className="mb-1 block font-heading text-3xl font-extrabold text-white max-[600px]:text-xl">
                {displays[i]}
              </span>
              <span className="text-xs font-medium text-white/50">{stat.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

// frontend/src/components/landing/HeroSection.vue
<template>
  <section class="hero">
    <!-- Background -->
    <div class="hero__bg">
      <img src="/images/hero-bg.png" alt="Masjid" class="hero__bg-img" />
      <div class="hero__overlay"></div>
    </div>

    <div class="hero__container container">
      <!-- Content -->
      <div class="hero__content">
        <p class="hero__label">LAZIS PLN BATAM — LEMBAGA ZAKAT, INFAQ & SHADAQAH</p>
        <h1 class="hero__title">
          Bergabunglah Bersama<br />
          kami dalam Misi <span class="hero__title-accent">Kebaikan</span>
        </h1>
        <p class="hero__desc">
          Kami berkomitmen untuk menyalurkan kebaikan bagi yang membutuhkan melalui program-program sosial transparan dan terpercaya.
        </p>
        <div class="hero__actions">
          <a href="#zakat-calculator" class="btn btn-gold">
            <svg viewBox="0 0 20 20" fill="currentColor" width="16" height="16"><path d="M10 2a8 8 0 100 16 8 8 0 000-16zm1 11H9v-2h2v2zm0-4H9V5h2v4z"/></svg>
            Tunaikan Zakat
          </a>
          <a href="#programs" class="btn btn-primary">Jelajahi Kami</a>
          <a href="#" class="btn btn-outline">Infaq / Shodaqoh</a>
        </div>
      </div>

      <!-- Feature Cards -->
      <div class="hero__features">
        <div class="hero__feature-card">
          <div class="hero__feature-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s-8-4.5-8-11.8A8 8 0 0112 2a8 8 0 018 8.2c0 7.3-8 11.8-8 11.8z"/><circle cx="12" cy="10" r="3"/></svg>
          </div>
          <div>
            <h4>Lembaga Amil Zakat</h4>
            <p>Resmi terdaftar dan diakui sebagai lembaga amil zakat yang amanah dan profesional.</p>
          </div>
        </div>
        <div class="hero__feature-card">
          <div class="hero__feature-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75"/></svg>
          </div>
          <div>
            <h4>Donasi Mudah</h4>
            <p>Proses donasi yang mudah dan cepat untuk menyalurkan zakat, infaq, dan shadaqah Anda.</p>
          </div>
        </div>
        <div class="hero__feature-card">
          <div class="hero__feature-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
          </div>
          <div>
            <h4>Transparan</h4>
            <p>Laporan penyaluran dana yang transparan dan dapat diakses oleh seluruh donatur.</p>
          </div>
        </div>
      </div>

      <!-- Stats -->
      <div class="hero__stats">
        <div class="hero__stat" v-for="stat in stats" :key="stat.label">
          <span class="hero__stat-value" ref="statRefs">{{ stat.display }}</span>
          <span class="hero__stat-label">{{ stat.label }}</span>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const stats = ref([
  { value: 3800000000, prefix: 'Rp ', suffix: ' M', display: 'Rp 0', label: 'Dana Terkumpul ZIS', divisor: 1000000 },
  { value: 1240, prefix: '', suffix: '+', display: '0', label: 'Donatur Aktif' },
  { value: 5600, prefix: '', suffix: '+', display: '0', label: 'Penerima Manfaat' },
  { value: 100, prefix: '', suffix: '%', display: '0%', label: 'Transparansi Dana' }
])

const animateCountUp = () => {
  stats.value.forEach((stat, index) => {
    let current = 0
    const target = stat.divisor ? stat.value / stat.divisor : stat.value
    const increment = target / 60
    const timer = setInterval(() => {
      current += increment
      if (current >= target) {
        current = target
        clearInterval(timer)
      }
      if (stat.divisor) {
        stat.display = `${stat.prefix}${(current / 1000).toFixed(1)}${stat.suffix}`
      } else {
        stat.display = `${stat.prefix}${Math.floor(current).toLocaleString('id-ID')}${stat.suffix}`
      }
    }, 16)
  })
}

onMounted(() => {
  setTimeout(animateCountUp, 500)
})
</script>

<style scoped>
.hero {
  position: relative;
  min-height: 100vh;
  display: flex;
  align-items: flex-end;
  padding-bottom: var(--space-2xl);
  overflow: hidden;
}

.hero__bg {
  position: absolute;
  inset: 0;
  z-index: 0;
}

.hero__bg-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.hero__overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(
    135deg,
    rgba(10, 46, 60, 0.92) 0%,
    rgba(10, 126, 126, 0.75) 50%,
    rgba(10, 46, 60, 0.85) 100%
  );
}

.hero__container {
  position: relative;
  z-index: 1;
  padding-top: 120px;
}

.hero__content {
  max-width: 650px;
  animation: fadeInUp 0.8s ease forwards;
}

.hero__label {
  font-size: var(--text-xs);
  font-weight: 600;
  color: var(--color-gold);
  letter-spacing: 2px;
  text-transform: uppercase;
  margin-bottom: var(--space-md);
}

.hero__title {
  font-family: var(--font-heading);
  font-size: var(--text-5xl);
  font-weight: 800;
  color: var(--color-white);
  line-height: 1.15;
  margin-bottom: var(--space-lg);
}

.hero__title-accent {
  color: var(--color-gold);
  font-style: italic;
}

.hero__desc {
  font-size: var(--text-lg);
  color: rgba(255, 255, 255, 0.8);
  line-height: 1.7;
  margin-bottom: var(--space-xl);
  max-width: 520px;
}

.hero__actions {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-md);
  margin-bottom: var(--space-3xl);
}

/* Feature Cards */
.hero__features {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--space-lg);
  margin-bottom: var(--space-2xl);
  animation: fadeInUp 0.8s ease 0.3s forwards;
  opacity: 0;
}

.hero__feature-card {
  display: flex;
  gap: var(--space-md);
  padding: var(--space-lg);
  background: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(12px);
  border: 1px solid rgba(255, 255, 255, 0.12);
  border-radius: var(--radius-lg);
  transition: all var(--transition-base);
}

.hero__feature-card:hover {
  background: rgba(255, 255, 255, 0.14);
  transform: translateY(-4px);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);
}

.hero__feature-icon {
  flex-shrink: 0;
  width: 44px;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-md);
  background: rgba(232, 185, 48, 0.15);
  color: var(--color-gold);
}

.hero__feature-icon svg {
  width: 22px;
  height: 22px;
}

.hero__feature-card h4 {
  font-size: var(--text-sm);
  font-weight: 700;
  color: var(--color-white);
  margin-bottom: 4px;
}

.hero__feature-card p {
  font-size: var(--text-xs);
  color: rgba(255, 255, 255, 0.6);
  line-height: 1.5;
}

/* Stats */
.hero__stats {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--space-lg);
  padding: var(--space-xl) var(--space-2xl);
  background: rgba(255, 255, 255, 0.06);
  backdrop-filter: blur(12px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: var(--radius-xl);
  animation: fadeInUp 0.8s ease 0.6s forwards;
  opacity: 0;
}

.hero__stat {
  text-align: center;
}

.hero__stat-value {
  display: block;
  font-family: var(--font-heading);
  font-size: var(--text-3xl);
  font-weight: 800;
  color: var(--color-white);
  margin-bottom: 4px;
}

.hero__stat-label {
  font-size: var(--text-xs);
  color: rgba(255, 255, 255, 0.5);
  font-weight: 500;
}

/* Responsive */
@media (max-width: 900px) {
  .hero__features {
    grid-template-columns: 1fr;
  }

  .hero__stats {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 600px) {
  .hero {
    min-height: auto;
    padding: 0 0 var(--space-2xl);
  }

  .hero__container {
    padding-top: 100px;
  }

  .hero__actions {
    flex-direction: column;
  }

  .hero__stats {
    padding: var(--space-lg);
  }

  .hero__stat-value {
    font-size: var(--text-xl);
  }
}
</style>
